import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sexchat Hot Cam Girls On Live Sex Cams, premium sexy contents On Sweetly  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png" />
             <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png" />
             <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png" />
             <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png" />
             <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png" />
             <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png" />
             <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png" />
             <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png" />
             <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png" />
             <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png" />
             <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
             <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png" />
             <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
             <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico" />

             <meta name="msapplication-TileColor" content="#ffffff" />
             <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png" />
             <meta name="theme-color" content="#ffffff" />
             <link rel="manifest" href="/favicon/manifest.json" />
             <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1>Sweetly</h1>
        <p className={styles.description}>
          <Image src="/logo_sweetly.svg" width="600" height="144" alt="" />
        </p>
        <h2>It's Coming!</h2>
        <p className={styles.description}>
        Indulge in the ultimate realm of premium adult content, meticulously curated to fulfill your wildest fantasies. Our collection encompasses a diverse array of tantalizing experiences, ranging from seductive videos to immersive storytelling and exclusive encounters. Immerse yourself in a world of uninhibited pleasure, where passion knows no boundaries. Our premium adult content offers unrivaled quality, featuring captivating performances and breathtaking visuals that will leave you craving for more. Unleash your desires and elevate your adult entertainment experience to new heights with our handpicked selection of premium adult content.
        </p>
      </main>

    </div>
  )
}

export default Home
